In [2]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

df=pd.read_csv("data.csv")

In [2]:
df.head()

,Customer_ID,Name,Age,City,Gender,Category,Product,Quantity,Price,Payment_Method
0,C101,Aarav,22,Hyderabad,M,Electronics,Headphones,1,2500,UPI
1,C102,Diya,25,Bangalore,F,Clothing,Hoodie,2,1800,Card
2,C103,Rohan,29,Chennai,M,Electronics,Keyboard,1,2200,UPI
3,C104,Ananya,21,Hyderabad,F,Beauty,Skincare_Set,3,1200,UPI
4,C105,Vikram,34,Mumbai,M,Home,Table_Lamp,2,900,Cash

In [3]:
df.shape
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     15 non-null     str
 1   Name            15 non-null     str
 2   Age             15 non-null     int64
 3   City            15 non-null     str
 4   Gender          15 non-null     str
 5   Category        15 non-null     str
 6   Product         15 non-null     str
 7   Quantity        15 non-null     int64
 8   Price           15 non-null     int64
 9   Payment_Method  15 non-null     str
dtypes: int64(3), str(7)
memory usage: 1.8 KB

Customer_ID       0
Name              0
Age               0
City              0
Gender            0
Category          0
Product           0
Quantity          0
Price             0
Payment_Method    0
dtype: int64

In [4]:
#creating a new column
df["Total_Amount"]=df["Quantity"]*df["Price"]

In [5]:
print(df["Total_Amount"].sum())

43500

In [6]:
print(df["Total_Amount"].mean())

2900.0

In [7]:
print(df["Total_Amount"].max())

4500

In [8]:
print(df["Total_Amount"].min())

1400

In [9]:
#filtering
#spent more than 3000
print(df["Total_Amount"]>3000)

0     False
1      True
2     False
3      True
4     False
5      True
6      True
7      True
8     False
9     False
10     True
11    False
12     True
13    False
14     True
Name: Total_Amount, dtype: bool

In [13]:
#are from hyd
print((df["City"]=="Hydarebad"))

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
Name: City, dtype: bool

In [14]:
#used UPI
print(df["Payment_Method"]=="UPI")

0      True
1     False
2      True
3      True
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14     True
Name: Payment_Method, dtype: bool

In [15]:
#bought electronics
print(df["Category"]=="Electronics")

0      True
1     False
2      True
3     False
4     False
5      True
6     False
7     False
8     False
9      True
10    False
11    False
12     True
13    False
14    False
Name: Category, dtype: bool

In [17]:
#sorting
#find the 5 highest value orders
df.sort_values("Total_Amount",ascending=False).head(5)

,Customer_ID,Name,Age,City,Gender,Category,Product,Quantity,Price,Payment_Method,Total_Amount
5,C106,Isha,27,Delhi,F,Electronics,Smartwatch,1,4500,Card,4500
7,C108,Meera,24,Bangalore,F,Beauty,Perfume,2,2100,Card,4200
3,C104,Ananya,21,Hyderabad,F,Beauty,Skincare_Set,3,1200,UPI,3600
14,C115,Manish,33,Chennai,M,Clothing,T_Shirt,4,900,UPI,3600
1,C102,Diya,25,Bangalore,F,Clothing,Hoodie,2,1800,Card,3600

In [18]:
#group by
#revenue by category
df.groupby("Category")["Total_Amount"].sum()

Category
Beauty          9800
Clothing       13600
Electronics    14100
Home            6000
Name: Total_Amount, dtype: int64

In [19]:
#revenue by city
df.groupby("City")["Total_Amount"].sum()

City
Bangalore    11300
Chennai       8200
Delhi         7700
Hyderabad    11300
Mumbai        5000
Name: Total_Amount, dtype: int64

In [20]:
#revenue by city
df.groupby("City")["Total_Amount"].sum()

City
Bangalore    11300
Chennai       8200
Delhi         7700
Hyderabad    11300
Mumbai        5000
Name: Total_Amount, dtype: int64

In [21]:
#revenue by payment methods
df.groupby("Payment_Method")["Total_Amount"].sum()

Payment_Method
Card    19000
Cash     6000
UPI     18500
Name: Total_Amount, dtype: int64

In [25]:
#which category generated the most revenue
category_revenue=df.groupby("Category")["Total_Amount"].sum()
print(category_revenue)
print("Highest",category_revenue.idxmax())

Category
Beauty          9800
Clothing       13600
Electronics    14100
Home            6000
Name: Total_Amount, dtype: int64
Highest Electronics

In [26]:
#which city has the highest spending
city_spend=df.groupby("City")["Total_Amount"].sum()
print(city_spend)
print("Highest: ",city_spend.idxmax())

City
Bangalore    11300
Chennai       8200
Delhi         7700
Hyderabad    11300
Mumbai        5000
Name: Total_Amount, dtype: int64
Highest:  Bangalore

In [27]:
#which payment method is most popular
payment_count = df["Payment_Method"].value_counts()

print(payment_count)

Payment_Method
UPI     7
Card    5
Cash    3
Name: count, dtype: int64

In [28]:
#which product sold the most unit
product_quantity=df.groupby("Product")["Quantity"].sum()
print(product_quantity)
print("Highest:", product_quantity.idxmax())

Product
Bedsheet        3
Cushion_Set     3
Face_Wash       4
Headphones      1
Hoodie          2
Jeans           2
Keyboard        1
Mouse           2
Perfume         2
Skincare_Set    3
Smartwatch      1
Sneakers        1
Speaker         1
T_Shirt         4
Table_Lamp      2
Name: Quantity, dtype: int64
Highest: Face_Wash

In [30]:
#who spent the most
highest_spender=df.loc[df["Total_Amount"].idxmax()]
print(highest_spender["Name"])
print(highest_spender["Total_Amount"])

Isha
4500

In [31]:
#whats the average age of customers
print(df["Age"].mean())

27.4

In [32]:
#which gender has higher spending
print(df.groupby("Gender")["Total_Amount"].sum())

Gender
F    21100
M    22400
Name: Total_Amount, dtype: int64

In [33]:
#which category has the highest average order value
print((df.groupby("Category")["Total_Amount"].mean()).idxmax)

<bound method Series.idxmax of Category
Beauty         3266.666667
Clothing       3400.000000
Electronics    2820.000000
Home           2000.000000
Name: Total_Amount, dtype: float64>

In [34]:
#find customers who spent more than 4k
high_spenders=df[df["Total_Amount"]>4000]
print(high_spenders[["Name","Total_Amount"]])

    Name  Total_Amount
5   Isha          4500
7  Meera          4200

In [35]:
#find the top 3 products bases on revenue
product_revenue=df.groupby("Product")["Total_Amount"].sum()
print(product_revenue.sort_values(ascending=False).head(3))

Product
Smartwatch    4500
Perfume       4200
Hoodie        3600
Name: Total_Amount, dtype: int64